name: A workflow for my web app demo
on: 
  workflow_dispatch:
  #push:
  #  paths:
  #    - '**'
  #    - '!.github/**'
jobs:
  build-job:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Check out code
    - name: Print content
      run: cat Index.html
